name: Build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cargo test --verbose

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Linux binary
        run: |
          cargo build --verbose --release --no-default-features --features rustls
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v2
        with:
          name: tracker-proxy-linux
          path: target/release/tracker-proxy

  build-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Windows environment
        run: |
          sudo apt install -y mingw-w64
          rustup target add x86_64-pc-windows-gnu
      - name: Build Windows binary
        run: |
          cargo build --verbose --release --no-default-features --features rustls --target x86_64-pc-windows-gnu
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v2
        with:
          name: tracker-proxy-windows.exe
          path: target/x86_64-pc-windows-gnu/release/tracker-proxy.exe
